# Use for testing
FROM ubuntu:14.04
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential libmysqlclient-dev python-mysqldb git
RUN pip install SQLAlchemy==1.2.19 && pip install psutil==5.7.0 && pip install flask
